language: python           

jobs:
  fast_finish: true
  include:
    - name: "Autolinks on Xenial Linux"
      python: 3.8           
      
    - name: "Autolinks on macOS"
      os: osx
      osx_image: xcode11.2  
      language: shell       
      
    - name: "Autolinks on Windows"
      os: windows           
      language: shell       
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      
install: pip3 install --upgrade pip  # all three OSes agree about 'pip3'

script: python3 my_app.py || python my_app.py

addons:
  hosts:
  - github.com
